config/routes.rb
Rails.application.routes.draw do
  resources :gardens, only: [:index, :show] do
    resources :plants, only: [:create]
  end

  resources :plants, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  validates :banner_url, presence: true

  has_many :plants, dependent: :destroy
end

app/models/plant.rb
class Plant < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  validates :image_url, presence: true

  belongs_to :garden
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  def index
    @gardens = Garden.all
  end

  def show
    @garden = Garden.find(params[:id])
    @plant = Plant.new
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def create
    # raise
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new(plant_params)
    @plant.garden = @garden
    if @plant.save
      redirect_to garden_path(@garden)
    else
      render 'gardens/show'
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy
    redirect_to garden_path(@plant.garden)
  end

  private

  def plant_params
    params.require(:plant).permit([:name, :image_url])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/index.html.erb
<div class="container">
  <h1>Gardens</h1>
  <ul>
    <% @gardens.each do |garden| %>
      <li>
        <%= link_to garden.name, garden_path(garden) %>
      </li>
    <% end %>
  </ul>
</div>

app/views/gardens/show.html.erb
<div class="banner mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @garden.banner_url %>);">
  <div class="container">
    <h1><%= @garden.name %></h1>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-8">
    <% if @garden.plants.present? %>
      <div class="container">
        <div class="row">
          <% @garden.plants.each do |plant| %>
            <div class="col-6">
              <div class="card-trip mb-3">
                <img src="<%= plant.image_url %>"/>
                <div class="card-trip-infos">
                  <div>
                    <h2><%= plant.name %></h2>
                  </div>
                  <%= link_to plant_path(plant), method: :delete, data: { confirm: "Are you sure you want to delete this plant?"} do %>
                    <h2 class="card-trip-pricing">🚮</h2>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% else %>
      <h2>No plants in this garden yet. Add some!</h2>
    <% end %>
    </div>
    <div class="col-4">
      <h2>Add a plant:</h2>
      <%= simple_form_for [@garden, @plant] do |f| %>
      <%= f.input :name, placeholder: "Bonzai tree" %>
      <%= f.input :image_url %>
      <%= f.submit "Add", class: "btn btn-primary" %>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardensAndPlants</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>